# Generated by Django 3.2.15 on 2022-11-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GPA', models.FloatField(null=True)),
                ('Research_Experience', models.PositiveIntegerField(choices=[(1, 'Has concept note'), (0, 'Has no concept note')], null=True)),
                ('TOEFL', models.FloatField(null=True)),
                ('Recommendation_Letter', models.PositiveIntegerField(null=True)),
                ('Problem_Statement', models.FloatField(null=True)),
                ('Probability', models.FloatField(null=True)),
                ('Status', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
