# Generated by Django 3.2.15 on 2022-11-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
