# Generated by Django 3.2.15 on 2022-11-06 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0004_auto_20221106_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Recommendation_Letter',
            new_name='LOR',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Probability',
            new_name='PROBABILITY',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Research_Experience',
            new_name='RCN',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='GPA',
            new_name='SOP',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='Problem_Statement',
            new_name='UGPA',
        ),
    ]
