# Generated by Django 3.2.15 on 2022-11-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0005_auto_20221106_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='Status',
            new_name='STATUS',
        ),
    ]
