# Generated by Django 4.1.3 on 2022-11-11 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_app', '0007_rename_name_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='TOEFL',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(120), django.core.validators.MinValueValidator(0)]),
        ),
    ]
